import { WordPair } from './types';

export const WORD_PAIRS: WordPair[] = [
  { civilian: 'Bánh mì', spy: 'Bánh bao' },
  { civilian: 'Mặt trời', spy: 'Mặt trăng' },
  { civilian: 'Bóng đá', spy: 'Bóng rổ' },
  { civilian: 'Cà phê', spy: 'Trà sữa' },
  { civilian: 'Mèo', spy: 'Chó' },
  { civilian: 'Máy bay', spy: 'Tàu hỏa' },
  { civilian: 'Điện thoại', spy: 'Máy tính' },
  { civilian: 'Mưa', spy: 'Tuyết' },
  { civilian: 'Biển', spy: 'Hồ' },
  { civilian: 'Sách', spy: 'Vở' },
  { civilian: 'Bút chì', spy: 'Bút bi' },
  { civilian: 'Mùa hè', spy: 'Mùa đông' },
  { civilian: 'Kem', spy: 'Sữa chua' },
  { civilian: 'Pizza', spy: 'Hamburger' },
  { civilian: 'Facebook', spy: 'Zalo' },
  { civilian: 'Youtube', spy: 'Tiktok' },
  { civilian: 'Đồng hồ', spy: 'Vòng tay' },
  { civilian: 'Giày', spy: 'Dép' },
  { civilian: 'Mũ', spy: 'Khăn quàng' },
  { civilian: 'Áo khoác', spy: 'Áo len' },
  { civilian: 'Cam', spy: 'Quýt' },
  { civilian: 'Táo', spy: 'Lê' },
  { civilian: 'Xoài', spy: 'Đu đủ' },
  { civilian: 'Dưa hấu', spy: 'Bưởi' },
  { civilian: 'Sầu riêng', spy: 'Mít' },
  { civilian: 'Nho', spy: 'Dâu tây' },
  { civilian: 'Chuối', spy: 'Ngô' },
  { civilian: 'Chanh', spy: 'Quất' },
  { civilian: 'Mận', spy: 'Đào' },
  { civilian: 'Vải', spy: 'Nhãn' },
  { civilian: 'Phở', spy: 'Bún bò' },
  { civilian: 'Hủ tiếu', spy: 'Bánh canh' },
  { civilian: 'Cơm tấm', spy: 'Cơm rang' },
  { civilian: 'Bánh xèo', spy: 'Bánh khọt' },
  { civilian: 'Gà rán', spy: 'Khoai tây chiên' },
  { civilian: 'Lẩu', spy: 'Nướng' },
  { civilian: 'Sushi', spy: 'Kimbap' },
  { civilian: 'Mì tôm', spy: 'Phở gói' },
  { civilian: 'Bánh quy', spy: 'Bánh bông lan' },
  { civilian: 'Sô cô la', spy: 'Kẹo mút' },
  { civilian: 'Pepsi', spy: 'Coca Cola' },
  { civilian: 'Bia', spy: 'Rượu' },
  { civilian: 'Nước suối', spy: 'Nước khoáng' },
  { civilian: 'Sữa tươi', spy: 'Sữa đậu nành' },
  { civilian: 'Nước ép', spy: 'Sinh tố' },
  { civilian: 'Hổ', spy: 'Báo' },
  { civilian: 'Sư tử', spy: 'Hổ' },
  { civilian: 'Voi', spy: 'Tê giác' },
  { civilian: 'Hươu cao cổ', spy: 'Đà điểu' },
  { civilian: 'Khỉ', spy: 'Vượn' },
  { civilian: 'Thỏ', spy: 'Sóc' },
  { civilian: 'Chuột', spy: 'Gián' },
  { civilian: 'Rắn', spy: 'Trăn' },
  { civilian: 'Cá mập', spy: 'Cá voi' },
  { civilian: 'Đại bàng', spy: 'Cú mèo' },
  { civilian: 'Gà', spy: 'Vịt' },
  { civilian: 'Lợn', spy: 'Bò' },
  { civilian: 'Ngựa', spy: 'Lừa' },
  { civilian: 'Ong', spy: 'Bướm' },
  { civilian: 'Kiến', spy: 'Mối' },
  { civilian: 'Laptop', spy: 'Macbook' },
  { civilian: 'iPad', spy: 'Máy tính bảng' },
  { civilian: 'Chuột máy tính', spy: 'Bàn phím' },
  { civilian: 'Tai nghe', spy: 'Loa' },
  { civilian: 'Tivi', spy: 'Máy chiếu' },
  { civilian: 'Tủ lạnh', spy: 'Máy giặt' },
  { civilian: 'Điều hòa', spy: 'Quạt máy' },
  { civilian: 'Bếp ga', spy: 'Bếp từ' },
  { civilian: 'Lò vi sóng', spy: 'Lò nướng' },
  { civilian: 'Máy hút bụi', spy: 'Chổi' },
  { civilian: 'Hà Nội', spy: 'Hải Phòng' },
  { civilian: 'TP.HCM', spy: 'Cần Thơ' },
  { civilian: 'Đà Nẵng', spy: 'Huế' },
  { civilian: 'Đà Lạt', spy: 'Sa Pa' },
  { civilian: 'Nha Trang', spy: 'Vũng Tàu' },
  { civilian: 'Phú Quốc', spy: 'Côn Đảo' },
  { civilian: 'Hạ Long', spy: 'Ninh Bình' },
  { civilian: 'Hội An', spy: 'Huế' },
  { civilian: 'Trung Quốc', spy: 'Nhật Bản' },
  { civilian: 'Mỹ', spy: 'Anh' },
  { civilian: 'Pháp', spy: 'Ý' },
  { civilian: 'Hàn Quốc', spy: 'Triều Tiên' },
  { civilian: 'Thái Lan', spy: 'Lào' },
  { civilian: 'Bóng chuyền', spy: 'Bóng ném' },
  { civilian: 'Cầu lông', spy: 'Tennis' },
  { civilian: 'Bơi lội', spy: 'Lặn' },
  { civilian: 'Chạy bộ', spy: 'Đi bộ' },
  { civilian: 'Gym', spy: 'Yoga' },
  { civilian: 'Cờ vua', spy: 'Cờ tướng' },
  { civilian: 'Bida', spy: 'Bowling' },
  { civilian: 'Bác sĩ', spy: 'Y tá' },
  { civilian: 'Giáo viên', spy: 'Giảng viên' },
  { civilian: 'Công an', spy: 'Bộ đội' },
  { civilian: 'Kỹ sư', spy: 'Kiến trúc sư' },
  { civilian: 'Ca sĩ', spy: 'Diễn viên' },
  { civilian: 'Họa sĩ', spy: 'Nhà văn' },
  { civilian: 'Đầu bếp', spy: 'Phục vụ' },
  { civilian: 'Tài xế', spy: 'Phi công' },
  { civilian: 'Nắng', spy: 'Gió' },
  { civilian: 'Mây', spy: 'Sương mù' },
  { civilian: 'Bão', spy: 'Lốc xoáy' },
  { civilian: 'Sấm sét', spy: 'Chớp' },
  { civilian: 'Núi', spy: 'Đồi' },
  { civilian: 'Rừng', spy: 'Vườn' },
  { civilian: 'Sa mạc', spy: 'Thảo nguyên' },
  { civilian: 'Sông', spy: 'Suối' },
  { civilian: 'Thác nước', spy: 'Đập thủy điện' },
  { civilian: 'Bình minh', spy: 'Hoàng hôn' },
  { civilian: 'Ban ngày', spy: 'Ban đêm' },
  { civilian: 'Mùa xuân', spy: 'Mùa thu' },
  { civilian: 'Tết', spy: 'Trung thu' },
  { civilian: 'Giáng sinh', spy: 'Halloween' },
  { civilian: 'Đám cưới', spy: 'Sinh nhật' },
  { civilian: 'Vali', spy: 'Balo' },
  { civilian: 'Ví tiền', spy: 'Túi xách' },
  { civilian: 'Ô (Dù)', spy: 'Áo mưa' },
  { civilian: 'Kính râm', spy: 'Kính cận' },
  { civilian: 'Nhẫn', spy: 'Dây chuyền' },
  { civilian: 'Son môi', spy: 'Phấn nền' },
  { civilian: 'Nước hoa', spy: 'Sữa tắm' },
  { civilian: 'Dầu gội', spy: 'Kem đánh răng' },
  { civilian: 'Giường', spy: 'Sofa' },
  { civilian: 'Bàn', spy: 'Ghế' },
  { civilian: 'Cửa sổ', spy: 'Cửa chính' },
  { civilian: 'Cầu thang', spy: 'Thang máy' },
  { civilian: 'Đèn trần', spy: 'Đèn ngủ' },
  { civilian: 'Gối', spy: 'Chăn' },
  { civilian: 'Gương', spy: 'Tranh treo tường' },
  { civilian: 'Đồng hồ báo thức', spy: 'Điện thoại' },
  { civilian: 'Bút lông', spy: 'Bút dạ' },
  { civilian: 'Bảng đen', spy: 'Bảng trắng' },
  { civilian: 'Cặp sách', spy: 'Túi chéo' },
  { civilian: 'Giấy A4', spy: 'Giấy kẻ ngang' },
  { civilian: 'Gọt bút chì', spy: 'Tẩy' },
  { civilian: 'Thước kẻ', spy: 'Compa' },
  { civilian: 'Keo dán', spy: 'Băng dính' },
  { civilian: 'Kéo', spy: 'Dao rọc giấy' },
  { civilian: 'Ghim bấm', spy: 'Kẹp giấy' },
  { civilian: 'Máy tính bỏ túi', spy: 'Điện thoại' },
  { civilian: 'Đèn bàn', spy: 'Đèn pin' },
  { civilian: 'Ổ cắm điện', spy: 'Phích cắm' },
  { civilian: 'Sạc dự phòng', spy: 'Cáp sạc' },
  { civilian: 'USB', spy: 'Thẻ nhớ' },
  { civilian: 'Chuột không dây', spy: 'Bàn di chuột' },
  { civilian: 'Màn hình', spy: 'Tivi' },
  { civilian: 'Bàn làm việc', spy: 'Bàn họp' },
  { civilian: 'Ghế xoay', spy: 'Ghế gỗ' },
  { civilian: 'Máy in', spy: 'Máy photocopy' },
  { civilian: 'Máy fax', spy: 'Máy quét (Scanner)' },
  { civilian: 'Tủ tài liệu', spy: 'Kệ sách' },
  { civilian: 'Thùng rác', spy: 'Giỏ đựng đồ' },
  { civilian: 'Cây nước nóng lạnh', spy: 'Ấm siêu tốc' },
  { civilian: 'Máy pha cà phê', spy: 'Máy xay sinh tố' },
  { civilian: 'Lò sưởi', spy: 'Quạt sưởi' },
  { civilian: 'Máy lọc không khí', spy: 'Máy tạo ẩm' },
  { civilian: 'Rèm cửa', spy: 'Mành sáo' },
  { civilian: 'Thảm trải sàn', spy: 'Chiếu' },
  { civilian: 'Gối ôm', spy: 'Gối tựa' },
  { civilian: 'Nệm', spy: 'Topper' },
  { civilian: 'Mắc áo', spy: 'Kẹp quần áo' },
  { civilian: 'Bàn là (ủi)', spy: 'Máy sấy tóc' },
  { civilian: 'Cân sức khỏe', spy: 'Thước dây' },
  { civilian: 'Bồn tắm', spy: 'Vòi hoa sen' },
  { civilian: 'Bồn cầu', spy: 'Chậu rửa mặt' },
  { civilian: 'Xà phòng', spy: 'Sữa tắm' },
  { civilian: 'Khăn tắm', spy: 'Khăn mặt' },
  { civilian: 'Bàn chải đánh răng', spy: 'Tăm nước' },
  { civilian: 'Dao cạo râu', spy: 'Máy cạo râu' },
  { civilian: 'Lược', spy: 'Kẹp tóc' },
  { civilian: 'Bông tẩy trang', spy: 'Khăn giấy' },
  { civilian: 'Nước súc miệng', spy: 'Chỉ nha khoa' },
  { civilian: 'Kem chống nắng', spy: 'Kem dưỡng da' },
  { civilian: 'Mặt nạ giấy', spy: 'Kem mắt' },
  { civilian: 'Tủ thuốc', spy: 'Hộp sơ cứu' },
  { civilian: 'Băng cá nhân', spy: 'Gạc y tế' },
  { civilian: 'Thuốc giảm đau', spy: 'Thuốc cảm' },
  { civilian: 'Vitamin', spy: 'Thực phẩm chức năng' },
  { civilian: 'Khẩu trang y tế', spy: 'Khẩu trang vải' },
  { civilian: 'Nước rửa tay', spy: 'Cồn y tế' },
  { civilian: 'Nhiệt kế', spy: 'Máy đo huyết áp' },
  { civilian: 'Xe đạp điện', spy: 'Xe máy điện' },
  { civilian: 'Xe tay ga', spy: 'Xe số' },
  { civilian: 'Xe hơi', spy: 'Xe tải' },
  { civilian: 'Xe khách', spy: 'Xe buýt' },
  { civilian: 'Tàu điện ngầm', spy: 'Tàu cao tốc' },
  { civilian: 'Thuyền buồm', spy: 'Du thuyền' },
  { civilian: 'Cano', spy: 'Mô tô nước' },
  { civilian: 'Khinh khí cầu', spy: 'Trực thăng' },
  { civilian: 'Sân bay', spy: 'Ga tàu' },
  { civilian: 'Bến xe', spy: 'Cảng biển' },
  { civilian: 'Trạm xăng', spy: 'Trạm sạc điện' },
  { civilian: 'Đèn giao thông', spy: 'Biển báo' },
  { civilian: 'Vạch kẻ đường', spy: 'Vỉa hè' },
  { civilian: 'Cầu vượt', spy: 'Hầm chui' },
  { civilian: 'Công viên', spy: 'Vườn hoa' },
  { civilian: 'Sở thú', spy: 'Thủy cung' },
  { civilian: 'Rạp chiếu phim', spy: 'Nhà hát' },
  { civilian: 'Bảo tàng', spy: 'Triển lãm' },
  { civilian: 'Thư viện', spy: 'Nhà sách' },
  { civilian: 'Siêu thị', spy: 'Chợ truyền thống' },
  { civilian: 'Trung tâm thương mại', spy: 'Cửa hàng tiện lợi' },
  { civilian: 'Nhà hàng', spy: 'Quán ăn vỉa hè' },
  { civilian: 'Quán cà phê', spy: 'Tiệm trà bánh' },
  { civilian: 'Phòng tập gym', spy: 'Sân bóng đá' },
  { civilian: 'Hồ bơi', spy: 'Bãi biển' },
  { civilian: 'Chùa', spy: 'Nhà thờ' },
  { civilian: 'Bệnh viện', spy: 'Phòng khám' },
  { civilian: 'Trường học', spy: 'Trung tâm ngoại ngữ' },
  { civilian: 'Ngân hàng', spy: 'Cây ATM' },
  { civilian: 'Bưu điện', spy: 'Công ty chuyển phát' },
  { civilian: 'Khách sạn', spy: 'Homestay' },
  { civilian: 'Văn phòng', spy: 'Co-working space' },
  { civilian: 'Nhà xưởng', spy: 'Kho bãi' },
  { civilian: 'Cánh đồng', spy: 'Trang trại' },
  { civilian: 'Vườn trái cây', spy: 'Nhà kính' },
  { civilian: 'Ao cá', spy: 'Chuồng gà' },
  { civilian: 'Núi lửa', spy: 'Động đất' },
  { civilian: 'Sóng thần', spy: 'Lũ lụt' },
  { civilian: 'Hạn hán', spy: 'Cháy rừng' },
  { civilian: 'Băng tan', spy: 'Hiệu ứng nhà kính' },
  { civilian: 'Rác thải nhựa', spy: 'Ô nhiễm không khí' },
  { civilian: 'Năng lượng mặt trời', spy: 'Năng lượng gió' },
  { civilian: 'Tái chế', spy: 'Phân loại rác' },
  { civilian: 'Trồng cây', spy: 'Phá rừng' },
  { civilian: 'Động vật hoang dã', spy: 'Thú cưng' },
  { civilian: 'Sinh vật biển', spy: 'Chim muông' },
  { civilian: 'Côn trùng', spy: 'Vi khuẩn' },
  { civilian: 'Khủng long', spy: 'Voi ma mút' },
];
